fix use of uninitialized variable and removed wrong and unused constants
rivosinc/veclibm pull request #32
Opened 2024-09-16 16:07 UTC by camel-cdr

I don't think there is a good/clean way to define the SNAN/QNAN/PINF/NINF/NEGZERO constants of type `sui64_fp64`, because the code wants to initialize them using floats, but the tests define `sui64_fp64` with `int64_t`.
That isn't portable, possible for unions.
Since the current value is wrong, and they aren't used, the easiest fix seems to be to remove them.

2024-09-20 09:18 UTC, luhenry requested changes

2024-09-20 09:18 UTC, luhenry commented on include/rvvlm_lgammaD.inc.h
> +  size_t vlen = VSETMAX();
It should be initialized to `VSET(_inarg_n);`, so it matches https://github.com/rivosinc/veclibm/pull/32/commits/0aff5807125da1fee7c79b45612d46d71f78dbf6#diff-72fcde0d45991c232db8b3be07c8c9fab9a8d09c48f6d3786aea5411074f3eabR491

2024-09-23 06:39 UTC, luhenry approved these changes

2024-09-23 07:17 UTC, keeranroth approved these changes

2024-09-23 12:17 UTC, merged